<?php

namespace Tests\Feature\ModelBased;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Facades\View;
use App\Models\Category;
use Tests\TestCase;

class NavigationTest extends TestCase
{
    use RefreshDatabase, WithoutMiddleware;

    protected $adapter;

    protected function setUp(): void
    {
        parent::setUp();

        View::share('category', Category::factory()->create([
            'name' => 'Test Category'
        ]));

        $this->adapter = new NavigationAdapter($this);
    }
    
    public function test_navigation_r()
    {
        $inputs = [
            "login",
            "open preview",
            "logout from post",
            "login",
            "open category",
            "create post",
            "fill form",
            "submit post",
            "logout from post",
            "login",
            "open preview",
            "logout from post",
            "login",
            "open category",
            "logout from list",
            "login",
            "logout from main",
            "login",
            "open preview",
            "logout from post",
            "login",
            "logout from main",
            "login",
            "open preview",
            "back to main from post",
            "open category",
            "open post",
            "back to category",
            "back to main from category",
            "open preview",
            "back to category",
            "open post",
            "back to category",
            "create post",
            "cancel"
        ];
            
        $this->adapter->runInputSequence($inputs);
    }

    public function test_navigation_tt()
    {
        $inputs = [
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "create post",
            "fill form",
            "submit post",
            "back to category",
            "open post",
            "back to main from post",
            "open category",
            "back to main from category",
            "open category",
            "create post",
            "cancel",
            "logout from list",
            "login",
            "open preview",
            "logout from post",
            "login",
            "logout from main"
        ];
            
        $this->adapter->runInputSequence($inputs);
    }

    public function test_navigation_ats()
    {
        $inputs = [
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "create post",
            "fill form",
            "submit post",
            "back to category",
            "open post",
            "back to main from post",
            "open category",
            "back to main from category",
            "open category",
            "create post",
            "cancel",
            "logout from list",
            "login",
            "open preview",
            "logout from post",
            "login",
            "logout from main",
            "login",
            "open category",
            "open post",
            "back to category",
            "create post",
            "fill form",
            "submit post",
            "logout from post",
            "login",
            "open category",
            "create post",
            "cancel",
            "logout from list",
            "login",
            "logout from main",
            "login",
            "open category",
            "create post",
            "fill form",
            "submit post",
            "logout from post",
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "create post",
            "cancel",
            "open post",
            "back to category",
            "back to main from category",
            "open preview",
            "logout from post",
            "login",
            "open preview",
            "back to main from post",
            "open preview",
            "logout from post",
            "login",
            "open preview",
            "back to category",
            "create post",
            "fill form"
        ];
            
        $this->adapter->runInputSequence($inputs);
    }

    public function test_navigation_1sc()
    {
        $inputs = [
            "login",
            "logout from main",
            "login",
            "open category",
            "logout from list",
            "login",
            "open preview",
            "logout from post",
            "login",
            "open category",
            "open post",
            "logout from post",
            "login",
            "open category",
            "back to main from category",
            "logout from main",
            "login",
            "open category",
            "create post",
            "fill form",
            "submit post",
            "logout from post",
            "login",
            "open preview",
            "back to category",
            "logout from list",
            "login",
            "open preview",
            "back to main from post",
            "logout from main",
            "login",
            "open preview",
            "back to category",
            "open post",
            "back to category",
            "back to main from category",
            "open category",
            "open post",
            "back to main from post",
            "open category",
            "back to main from category",
            "open preview",
            "back to category",
            "create post",
            "cancel",
            "logout from list",
            "login",
            "open preview",
            "back to main from post",
            "open preview",
            "back to category",
            "create post",
            "fill form",
            "cancel",
            "logout from list",
            "login",
            "open category",
            "create post",
            "cancel",
            "open post",
            "back to category",
            "create post",
            "cancel",
            "back to main from category",
            "open category",
            "create post",
            "cancel",
            "create post",
            "fill form",
            "submit post",
            "back to category",
            "create post",
            "fill form",
            "submit post",
            "back to main from post",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "open post",
            "back to category",
            "create post",
            "fill form",
            "cancel",
            "back to main from category",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "create post"
        ];
            
        $this->adapter->runInputSequence($inputs);
    }

    public function test_navigation_hsi()
    {
        $inputs = [
            "<reset>",
            "login",
            "open preview",
            "login",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "login",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "login",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "login",
            "login",
            "<reset>",
            "login",
            "open preview",
            "logout from post",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "logout from post",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "logout from post",
            "login",
            "<reset>",
            "login",
            "open preview",
            "submit post",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "submit post",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "submit post",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "submit post",
            "login",
            "<reset>",
            "login",
            "open preview",
            "fill form",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "fill form",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "fill form",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "fill form",
            "login",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "submit post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "submit post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "submit post",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "submit post",
            "login",
            "<reset>",
            "login",
            "open category",
            "create post",
            "submit post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "submit post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "login",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "login",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "login",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "login",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "login",
            "login",
            "<reset>",
            "login",
            "open category",
            "logout from post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "logout from post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "logout from post",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "logout from post",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "logout from post",
            "login",
            "<reset>",
            "login",
            "open category",
            "open preview",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "open preview",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "open preview",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "open preview",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "open preview",
            "login",
            "<reset>",
            "login",
            "open category",
            "submit post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "submit post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "submit post",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "submit post",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "submit post",
            "login",
            "<reset>",
            "login",
            "open category",
            "fill form",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "fill form",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "fill form",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "fill form",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "fill form",
            "login",
            "<reset>",
            "login",
            "login",
            "fill form",
            "<reset>",
            "login",
            "login",
            "submit post",
            "<reset>",
            "login",
            "login",
            "open preview",
            "<reset>",
            "login",
            "login",
            "logout from post",
            "<reset>",
            "login",
            "login",
            "login",
            "<reset>",
            "login",
            "logout from post",
            "fill form",
            "<reset>",
            "login",
            "logout from post",
            "submit post",
            "<reset>",
            "login",
            "logout from post",
            "open preview",
            "<reset>",
            "login",
            "logout from post",
            "logout from post",
            "<reset>",
            "login",
            "logout from post",
            "login",
            "<reset>",
            "login",
            "submit post",
            "fill form",
            "<reset>",
            "login",
            "submit post",
            "submit post",
            "<reset>",
            "login",
            "submit post",
            "open preview",
            "<reset>",
            "login",
            "submit post",
            "logout from post",
            "<reset>",
            "login",
            "submit post",
            "login",
            "<reset>",
            "login",
            "fill form",
            "fill form",
            "<reset>",
            "login",
            "fill form",
            "submit post",
            "<reset>",
            "login",
            "fill form",
            "open preview",
            "<reset>",
            "login",
            "fill form",
            "logout from post",
            "<reset>",
            "login",
            "fill form",
            "login",
            "<reset>",
            "submit post",
            "fill form",
            "<reset>",
            "submit post",
            "submit post",
            "<reset>",
            "submit post",
            "login",
            "<reset>",
            "fill form",
            "fill form",
            "<reset>",
            "fill form",
            "submit post",
            "<reset>",
            "fill form",
            "login",
            "<reset>",
            "back to category",
            "fill form",
            "<reset>",
            "back to category",
            "submit post",
            "<reset>",
            "back to category",
            "login",
            "<reset>",
            "back to main from category",
            "fill form",
            "<reset>",
            "back to main from category",
            "submit post",
            "<reset>",
            "back to main from category",
            "login",
            "<reset>",
            "back to main from post",
            "fill form",
            "<reset>",
            "back to main from post",
            "submit post",
            "<reset>",
            "back to main from post",
            "login",
            "<reset>",
            "cancel",
            "fill form",
            "<reset>",
            "cancel",
            "submit post",
            "<reset>",
            "cancel",
            "login",
            "<reset>",
            "create post",
            "fill form",
            "<reset>",
            "create post",
            "submit post",
            "<reset>",
            "create post",
            "login",
            "<reset>",
            "logout from list",
            "fill form",
            "<reset>",
            "logout from list",
            "submit post",
            "<reset>",
            "logout from list",
            "login",
            "<reset>",
            "logout from main",
            "fill form",
            "<reset>",
            "logout from main",
            "submit post",
            "<reset>",
            "logout from main",
            "login",
            "<reset>",
            "logout from post",
            "fill form",
            "<reset>",
            "logout from post",
            "submit post",
            "<reset>",
            "logout from post",
            "login",
            "<reset>",
            "open category",
            "fill form",
            "<reset>",
            "open category",
            "submit post",
            "<reset>",
            "open category",
            "login",
            "<reset>",
            "open post",
            "fill form",
            "<reset>",
            "open post",
            "submit post",
            "<reset>",
            "open post",
            "login",
            "<reset>",
            "open preview",
            "fill form",
            "<reset>",
            "open preview",
            "submit post",
            "<reset>",
            "open preview",
            "login",
            "<reset>",
            "login",
            "back to category",
            "fill form",
            "<reset>",
            "login",
            "back to category",
            "submit post",
            "<reset>",
            "login",
            "back to category",
            "open preview",
            "<reset>",
            "login",
            "back to category",
            "logout from post",
            "<reset>",
            "login",
            "back to category",
            "login",
            "<reset>",
            "login",
            "back to main from category",
            "fill form",
            "<reset>",
            "login",
            "back to main from category",
            "submit post",
            "<reset>",
            "login",
            "back to main from category",
            "open preview",
            "<reset>",
            "login",
            "back to main from category",
            "logout from post",
            "<reset>",
            "login",
            "back to main from category",
            "login",
            "<reset>",
            "login",
            "back to main from post",
            "fill form",
            "<reset>",
            "login",
            "back to main from post",
            "submit post",
            "<reset>",
            "login",
            "back to main from post",
            "open preview",
            "<reset>",
            "login",
            "back to main from post",
            "logout from post",
            "<reset>",
            "login",
            "back to main from post",
            "login",
            "<reset>",
            "login",
            "cancel",
            "fill form",
            "<reset>",
            "login",
            "cancel",
            "submit post",
            "<reset>",
            "login",
            "cancel",
            "open preview",
            "<reset>",
            "login",
            "cancel",
            "logout from post",
            "<reset>",
            "login",
            "cancel",
            "login",
            "<reset>",
            "login",
            "create post",
            "fill form",
            "<reset>",
            "login",
            "create post",
            "submit post",
            "<reset>",
            "login",
            "create post",
            "open preview",
            "<reset>",
            "login",
            "create post",
            "logout from post",
            "<reset>",
            "login",
            "create post",
            "login",
            "<reset>",
            "login",
            "logout from list",
            "fill form",
            "<reset>",
            "login",
            "logout from list",
            "submit post",
            "<reset>",
            "login",
            "logout from list",
            "open preview",
            "<reset>",
            "login",
            "logout from list",
            "logout from post",
            "<reset>",
            "login",
            "logout from list",
            "login",
            "<reset>",
            "login",
            "logout from main",
            "fill form",
            "<reset>",
            "login",
            "logout from main",
            "submit post",
            "<reset>",
            "login",
            "logout from main",
            "login",
            "<reset>",
            "login",
            "open post",
            "fill form",
            "<reset>",
            "login",
            "open post",
            "submit post",
            "<reset>",
            "login",
            "open post",
            "open preview",
            "<reset>",
            "login",
            "open post",
            "logout from post",
            "<reset>",
            "login",
            "open post",
            "login",
            "<reset>",
            "login",
            "open category",
            "back to category",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "back to category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "back to category",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "back to category",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "back to category",
            "login",
            "<reset>",
            "login",
            "open category",
            "back to main from category",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "back to main from category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "back to main from category",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "back to main from category",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "back to main from category",
            "login",
            "<reset>",
            "login",
            "open category",
            "back to main from post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "back to main from post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "back to main from post",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "back to main from post",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "back to main from post",
            "login",
            "<reset>",
            "login",
            "open category",
            "cancel",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "cancel",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "cancel",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "cancel",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "cancel",
            "login",
            "<reset>",
            "login",
            "open category",
            "logout from list",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "logout from list",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "logout from list",
            "login",
            "<reset>",
            "login",
            "open category",
            "logout from main",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "logout from main",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "logout from main",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "logout from main",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "logout from main",
            "login",
            "<reset>",
            "login",
            "open category",
            "open category",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "open category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "open category",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "open category",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "open category",
            "login",
            "<reset>",
            "login",
            "open category",
            "open post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "open post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "open post",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "open post",
            "login",
            "<reset>",
            "login",
            "open category",
            "create post",
            "back to category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "back to category",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "back to main from category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "back to main from category",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "back to main from post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "back to main from post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "cancel",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "cancel",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "cancel",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "create post",
            "cancel",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "cancel",
            "login",
            "<reset>",
            "login",
            "open category",
            "create post",
            "create post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "create post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "login",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "login",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "logout from list",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "logout from list",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "logout from main",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "logout from main",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "logout from post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "logout from post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "open category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "open category",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "open post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "open post",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "open preview",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "open preview",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "back to category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "back to main from category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "back to main from post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "fill form",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "open preview",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "logout from post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "cancel",
            "login",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "create post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "fill form",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "login",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "logout from list",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "logout from main",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "logout from post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "open category",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "open post",
            "submit post",
            "<reset>",
            "login",
            "open category",
            "create post",
            "fill form",
            "open preview",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "back to category",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "back to category",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "back to category",
            "open preview",
            "<reset>",
            "login",
            "open preview",
            "back to category",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "back to category",
            "login",
            "<reset>",
            "login",
            "open preview",
            "back to main from category",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "back to main from category",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "back to main from category",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "back to main from category",
            "login",
            "<reset>",
            "login",
            "open preview",
            "back to main from post",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "back to main from post",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "back to main from post",
            "open preview",
            "<reset>",
            "login",
            "open preview",
            "back to main from post",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "back to main from post",
            "login",
            "<reset>",
            "login",
            "open preview",
            "cancel",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "cancel",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "cancel",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "cancel",
            "login",
            "<reset>",
            "login",
            "open preview",
            "create post",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "create post",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "create post",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "create post",
            "login",
            "<reset>",
            "login",
            "open preview",
            "logout from list",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "logout from list",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "logout from list",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "logout from list",
            "login",
            "<reset>",
            "login",
            "open preview",
            "logout from main",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "logout from main",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "logout from main",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "logout from main",
            "login",
            "<reset>",
            "login",
            "open preview",
            "open category",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "open category",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "open category",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "open category",
            "login",
            "<reset>",
            "login",
            "open preview",
            "open post",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "open post",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "open post",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "open post",
            "login",
            "<reset>",
            "login",
            "open preview",
            "open preview",
            "fill form",
            "<reset>",
            "login",
            "open preview",
            "open preview",
            "submit post",
            "<reset>",
            "login",
            "open preview",
            "open preview",
            "logout from post",
            "<reset>",
            "login",
            "open preview",
            "open preview",
            "login"
        ];
            
        $this->adapter->runInputSequence($inputs);
    }
}